simplify code
Signed-off-by: chensuyue <suyue.chen@intel.com>

diff --git a/.github/workflows/_docker-compose-run.yml b/.github/workflows/_docker-compose-run.yml
--- a/.github/workflows/_docker-compose-run.yml
+++ b/.github/workflows/_docker-compose-run.yml
@@ -63,16 +63,42 @@ jobs:
       runs-on: ${{ inputs.hardware }}
       continue-on-error: true
       steps:
+        - name: Clean up Working Directory
+          run: sudo rm -rf ${{github.workspace}}/*
+
         - name: Checkout out Repo
           uses: actions/checkout@v4
           with:
             ref: ${{ needs.Get-test-case.outputs.CHECKOUT_REF }}
             fetch-depth: 0
+
         - name: Run test
-          uses: ./.github/workflows/actions/docker-compose-test
+          shell: bash
+          env:
+            HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
+            GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
+            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
+            IMAGE_REPO: ${{ inputs.registry }}
+            IMAGE_TAG: ${{ inputs.tag }}
+            example: ${{ inputs.example }}
+            hardware: ${{ inputs.hardware }}
+            test_case: ${{ matrix.test_case }}
+          run: |
+            cd ${{ github.workspace }}/$example/tests
+            export IMAGE_REPO=${OPEA_IMAGE_REPO}
+            if [ -f ${test_case} ]; then timeout 30m bash ${test_case}; else echo "Test script {${test_case}} not found, skip test!"; fi
+
+        - name: Clean up container
+          shell: bash
+          if: cancelled() || failure()
+          run: |
+            cd ${{ github.workspace }}/${{ inputs.example }}/docker/${{ inputs.hardware }}
+            docker compose stop && docker compose rm -f
+            echo y | docker system prune --all
+
+        - name: Publish pipeline artifact
+          if: ${{ !cancelled() }}
+          uses: actions/upload-artifact@v4
           with:
-              registry: ${{ inputs.registry }}
-              tag: ${{ inputs.tag }}
-              example: ${{ inputs.example }}
-              test_case: ${{ matrix.test_case }}
-              hardware: ${{ inputs.hardware }}
+            name: ${{ inputs.test_case }}
+            path: ${{ github.workspace }}/${{ inputs.example }}/tests/*.log
