Fix
Signed-off-by: ZePan110 <ze.pan@intel.com>

diff --git a/.github/workflows/_helm-e2e.yml b/.github/workflows/_helm-e2e.yml
--- a/.github/workflows/_helm-e2e.yml
+++ b/.github/workflows/_helm-e2e.yml
@@ -131,24 +131,28 @@ jobs:
           ref: ${{ steps.get-checkout-ref.outputs.CHECKOUT_REF }}
           fetch-depth: 0
 
-      - name: Validate Inputs
-        run: |
-          cd ${{ github.workspace }}
-          # folders=($(find . -maxdepth 1 -type d ! -name ".*" -printf "%f\n" | tr '[:upper:]' '[:lower:]'))
-          folders=(${{ vars.NIGHTLY_RELEASE_EXAMPLES }})
-          echo "folders: ${folders[@]}"
-          echo "example: ${{ inputs.example }}"
-          example_lower=$(echo "${{ inputs.example }}" | tr '[:upper:]' '[:lower:]')
-          if [[ ! " ${folders[@]} " =~ " ${example_lower} " ]]; then
-            echo "Error: Input '${example_lower}' is not in the list of folders."
-            exit 1
-          fi
+      # - name: Validate Inputs
+      #   run: |
+      #     cd ${{ github.workspace }}
+      #     # folders=($(find . -maxdepth 1 -type d ! -name ".*" -printf "%f\n" | tr '[:upper:]' '[:lower:]'))
+      #     folders=(${{ vars.NIGHTLY_RELEASE_EXAMPLES }})
+      #     echo "folders: ${folders[@]}"
+      #     echo "example: ${{ inputs.example }}"
+      #     example_lower=$(echo "${{ inputs.example }}" | tr '[:upper:]' '[:lower:]')
+      #     if [[ ! " ${folders[@]} " =~ " ${example_lower} " ]]; then
+      #       echo "Error: Input '${example_lower}' is not in the list of folders."
+      #       exit 1
+      #     fi
+          # if [[ ! "${example_lower}" =~ ^[a-z0-9-]+$ ]]; then
+          #   echo "Error: Input '${example_lower}' contains invalid characters. Only alphanumeric characters and dashes are allowed."
+          #   exit 1
+          # fi
 
       - name: Set variables
         env:
           example: ${{ inputs.example }}
         run: |
-          CHART_NAME="${example,,}"  # CodeGen
+          CHART_NAME=$(echo "${example,,}" | tr -cd 'a-z0-9-')  # CodeGen
           echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
           echo "RELEASE_NAME=${CHART_NAME}$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
           echo "NAMESPACE=${CHART_NAME}-$(head -c 4 /dev/urandom | xxd -p)" >> $GITHUB_ENV
