bug fix
Signed-off-by: chensuyue <suyue.chen@intel.com>

diff --git a/.github/workflows/_run-docker-compose.yml b/.github/workflows/_run-docker-compose.yml
--- a/.github/workflows/_run-docker-compose.yml
+++ b/.github/workflows/_run-docker-compose.yml
@@ -25,7 +25,7 @@ on:
         required: true
         type: string
 jobs:
-  Get-test-case:
+  get-test-case:
     runs-on: ubuntu-latest
     outputs:
       test_cases: ${{ steps.test-case-matrix.outputs.test_cases }}
@@ -35,11 +35,12 @@ jobs:
         id: get-checkout-ref
         run: |
           if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
-            echo "CHECKOUT_REF=refs/pull/${{ github.event.number }}/merge" >> $GITHUB_OUTPUT
+            CHECKOUT_REF=refs/pull/${{ github.event.number }}/merge
           else
-            echo "CHECKOUT_REF=${{ github.ref }}" >> $GITHUB_OUTPUT
+            CHECKOUT_REF=${{ github.ref }}
           fi
-          echo "checkout ref ${{ env.CHECKOUT_REF }}"
+          echo "CHECHOUT_REF=${CHECKOUT_REF}" >> $GITHUB_OUTPUT
+          echo "checkout ref ${CHECKOUT_REF}"
 
       - name: Checkout out Repo
         uses: actions/checkout@v4
@@ -48,59 +49,61 @@ jobs:
           fetch-depth: 0
 
       - name: Get test matrix
+        shell: bash
         id: test-case-matrix
         run: |
-          example_l=$(echo $example | tr '[:upper:]' '[:lower:]')
+          set -x
+          example_l=$(echo ${{ inputs.example }} | tr '[:upper:]' '[:lower:]')
           cd ${{ github.workspace }}/${{ inputs.example }}/tests
-          test_cases=$(find . -type f -name 'test_${example_l}*on_${{ inputs.hardware }}.sh' -print | cut -d/ -f2 | jq -R '.' | jq -sc '.')
+          test_cases=$(find . -type f -name "test_${example_l}*on_${{ inputs.hardware }}.sh" -print | cut -d/ -f2 | jq -R '.' | jq -sc '.')
           echo "test_cases=$test_cases" >> $GITHUB_OUTPUT
 
-  Run-test:
-      needs: [Get-test-case]
-      strategy:
-        matrix:
-          test_case: ${{ fromJSON(needs.Get-test-case.outputs.test_cases) }}
-      runs-on: ${{ inputs.hardware }}
-      continue-on-error: true
-      steps:
-        - name: Clean up Working Directory
-          run: |
-            sudo rm -rf ${{github.workspace}}/*
-            echo y | docker system prune --all
+  run-test:
+    needs: [get-test-case]
+    strategy:
+      matrix:
+        test_case: ${{ fromJSON(needs.get-test-case.outputs.test_cases) }}
+    runs-on: ${{ inputs.hardware }}
+    continue-on-error: true
+    steps:
+      - name: Clean up Working Directory
+        run: |
+          sudo rm -rf ${{github.workspace}}/*
+          echo y | docker system prune --all
 
-        - name: Checkout out Repo
-          uses: actions/checkout@v4
-          with:
-            ref: ${{ needs.Get-test-case.outputs.CHECKOUT_REF }}
-            fetch-depth: 0
+      - name: Checkout out Repo
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ needs.get-test-case.outputs.CHECKOUT_REF }}
+          fetch-depth: 0
 
-        - name: Run test
-          shell: bash
-          env:
-            HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
-            GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
-            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
-            IMAGE_REPO: ${{ inputs.registry }}
-            IMAGE_TAG: ${{ inputs.tag }}
-            example: ${{ inputs.example }}
-            hardware: ${{ inputs.hardware }}
-            test_case: ${{ matrix.test_case }}
-          run: |
-            cd ${{ github.workspace }}/$example/tests
-            export IMAGE_REPO=${OPEA_IMAGE_REPO}
-            if [ -f ${test_case} ]; then timeout 30m bash ${test_case}; else echo "Test script {${test_case}} not found, skip test!"; fi
+      - name: Run test
+        shell: bash
+        env:
+          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
+          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
+          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
+          IMAGE_REPO: ${{ inputs.registry }}
+          IMAGE_TAG: ${{ inputs.tag }}
+          example: ${{ inputs.example }}
+          hardware: ${{ inputs.hardware }}
+          test_case: ${{ matrix.test_case }}
+        run: |
+          cd ${{ github.workspace }}/$example/tests
+          export IMAGE_REPO=${OPEA_IMAGE_REPO}
+          if [ -f ${test_case} ]; then timeout 30m bash ${test_case}; else echo "Test script {${test_case}} not found, skip test!"; fi
 
-        - name: Clean up container
-          shell: bash
-          if: cancelled() || failure()
-          run: |
-            cd ${{ github.workspace }}/${{ inputs.example }}/docker/${{ inputs.hardware }}
-            docker compose stop && docker compose rm -f
-            echo y | docker system prune --all
+      - name: Clean up container
+        shell: bash
+        if: cancelled() || failure()
+        run: |
+          cd ${{ github.workspace }}/${{ inputs.example }}/docker/${{ inputs.hardware }}
+          docker compose stop && docker compose rm -f
+          echo y | docker system prune --all
 
-        - name: Publish pipeline artifact
-          if: ${{ !cancelled() }}
-          uses: actions/upload-artifact@v4
-          with:
-            name: ${{ inputs.test_case }}
-            path: ${{ github.workspace }}/${{ inputs.example }}/tests/*.log
+      - name: Publish pipeline artifact
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ inputs.test_case }}
+          path: ${{ github.workspace }}/${{ inputs.example }}/tests/*.log
