test
Signed-off-by: Sun, Xuehao <xuehao.sun@intel.com>

diff --git a/.github/workflows/ChatQnA_xeon.yml b/.github/workflows/ChatQnA_xeon.yml
--- a/.github/workflows/ChatQnA_xeon.yml
+++ b/.github/workflows/ChatQnA_xeon.yml
@@ -40,15 +40,15 @@ jobs:
           cd ${{ github.workspace }}/ChatQnA/tests
           timeout 20m bash test_chatqna_on_xeon.sh
 
-      - name: Clean Up Container
-        if: cancelled() || failure()
-        run: |
-          cd ${{ github.workspace }}/ChatQnA/microservice/xeon
-          container_list=$(cat docker_compose.yaml | grep container_name | cut -d':' -f2)
-          for container_name in $container_list; do
-              cid=$(docker ps -aq --filter "name=$container_name")
-              if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
-          done
+      # - name: Clean Up Container
+      #   if: cancelled() || failure()
+      #   run: |
+      #     cd ${{ github.workspace }}/ChatQnA/microservice/xeon
+      #     container_list=$(cat docker_compose.yaml | grep container_name | cut -d':' -f2)
+      #     for container_name in $container_list; do
+      #         cid=$(docker ps -aq --filter "name=$container_name")
+      #         if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
+      #     done
 
       - name: Publish backend test artifact
         if: ${{ !cancelled() }}
