[skip ci] for debug
Signed-off-by: chensuyue <suyue.chen@intel.com>

diff --git a/.github/workflows/CodeGen_xeon.yml b/.github/workflows/CodeGen_xeon.yml
--- a/.github/workflows/CodeGen_xeon.yml
+++ b/.github/workflows/CodeGen_xeon.yml
@@ -40,15 +40,15 @@ jobs:
           cd ${{ github.workspace }}/CodeGen/tests
           timeout 20m bash test_codegen_on_xeon.sh
 
-      - name: Clean Up Container
-        if: cancelled() || failure()
-        run: |
-          cd ${{ github.workspace }}/CodeGen/docker-composer/xeon
-          container_list=$(cat docker_compose.yaml | grep container_name | cut -d':' -f2)
-          for container_name in $container_list; do
-              cid=$(docker ps -aq --filter "name=$container_name")
-              if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
-          done
+#      - name: Clean Up Container
+#        if: cancelled() || failure()
+#        run: |
+#          cd ${{ github.workspace }}/CodeGen/docker-composer/xeon
+#          container_list=$(cat docker_compose.yaml | grep container_name | cut -d':' -f2)
+#          for container_name in $container_list; do
+#              cid=$(docker ps -aq --filter "name=$container_name")
+#              if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
+#          done
 
       - name: Publish pipeline artifact
         if: ${{ !cancelled() }}
