test
Signed-off-by: ZePan110 <ze.pan@intel.com>

diff --git a/.github/workflows/manual-docker-scan.yml b/.github/workflows/manual-docker-scan.yml
--- a/.github/workflows/manual-docker-scan.yml
+++ b/.github/workflows/manual-docker-scan.yml
@@ -44,71 +44,84 @@ jobs:
       examples: ${{ inputs.examples }}
       images: ${{ inputs.images }}
 
-  scan-docker:
+  test:
     needs: get-image-list
     runs-on: "docker-build-${{ inputs.node }}"
-    if: ${{ needs.get-image-list.outputs.matrix != '' }}
+    if: ${{ needs.get-image-list.outputs.run_matrix != '' }}
     strategy:
-      matrix:
-        image: ${{ fromJson(needs.get-image-list.outputs.matrix) }}
+      matrix: ${{ fromJSON(needs.get-image-list.outputs.run_matrix) }}
       fail-fast: false
     steps:
-      - name: Clean up Working Directory
+      - name: test output
         run: |
-          sudo rm -rf ${{github.workspace}}/* || true
-          docker system prune -f
+          echo "Image: ${{ matrix.image }}"
+          echo "Dockerfile: ${{ matrix.dockerfile }}"
 
-      - name: Pull Image
-        run: |
-          docker pull ${OPEA_IMAGE_REPO}opea/${{ matrix.image }}:${{ inputs.tag }}
-          echo "OPEA_IMAGE_REPO=${OPEA_IMAGE_REPO}" >> $GITHUB_ENV
+  # scan-docker:
+  #   needs: get-image-list
+  #   runs-on: "docker-build-${{ inputs.node }}"
+  #   if: ${{ needs.get-image-list.outputs.matrix != '' }}
+  #   strategy:
+  #     matrix:
+  #       image: ${{ fromJson(needs.get-image-list.outputs.matrix) }}
+  #     fail-fast: false
+  #   steps:
+  #     - name: Clean up Working Directory
+  #       run: |
+  #         sudo rm -rf ${{github.workspace}}/* || true
+  #         docker system prune -f
 
-      - name: SBOM Scan Container
-        uses: anchore/sbom-action@v0.17.1
-        if: ${{ inputs.sbom_scan }}
-        with:
-          image: ${{ env.OPEA_IMAGE_REPO }}opea/${{ matrix.image }}:${{ inputs.tag }}
-          output-file: ${{ matrix.image }}-sbom-scan.txt
-          format: 'spdx-json'
+  #     - name: Pull Image
+  #       run: |
+  #         docker pull ${OPEA_IMAGE_REPO}opea/${{ matrix.image }}:${{ inputs.tag }}
+  #         echo "OPEA_IMAGE_REPO=${OPEA_IMAGE_REPO}" >> $GITHUB_ENV
 
-      - name: Security Scan Container
-        uses: aquasecurity/trivy-action@0.24.0
-        if: ${{ inputs.trivy_scan }}
-        with:
-          image-ref: ${{ env.OPEA_IMAGE_REPO }}opea/${{ matrix.image }}:${{ inputs.tag }}
-          output: ${{ matrix.image }}-trivy-scan.txt
-          format: 'table'
-          exit-code: '1'
-          ignore-unfixed: true
-          vuln-type: 'os,library'
-          severity: 'CRITICAL,HIGH'
+  #     - name: SBOM Scan Container
+  #       uses: anchore/sbom-action@v0.17.1
+  #       if: ${{ inputs.sbom_scan }}
+  #       with:
+  #         image: ${{ env.OPEA_IMAGE_REPO }}opea/${{ matrix.image }}:${{ inputs.tag }}
+  #         output-file: ${{ matrix.image }}-sbom-scan.txt
+  #         format: 'spdx-json'
 
-      - name: Cleanup
-        if: always()
-        run: docker rmi -f ${OPEA_IMAGE_REPO}opea/${{ matrix.image }}:${{ inputs.tag }} || true
+  #     - name: Security Scan Container
+  #       uses: aquasecurity/trivy-action@0.24.0
+  #       if: ${{ inputs.trivy_scan }}
+  #       with:
+  #         image-ref: ${{ env.OPEA_IMAGE_REPO }}opea/${{ matrix.image }}:${{ inputs.tag }}
+  #         output: ${{ matrix.image }}-trivy-scan.txt
+  #         format: 'table'
+  #         exit-code: '1'
+  #         ignore-unfixed: true
+  #         vuln-type: 'os,library'
+  #         severity: 'CRITICAL,HIGH'
 
-      - name: Collect Logs
-        if: always()
-        run: |
-          mkdir -p /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}
-          mv ${{ matrix.image }}-*-scan.txt /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}
+  #     - name: Cleanup
+  #       if: always()
+  #       run: docker rmi -f ${OPEA_IMAGE_REPO}opea/${{ matrix.image }}:${{ inputs.tag }} || true
 
-  upload-artifacts:
-    needs: scan-docker
-    runs-on: "docker-build-${{ inputs.node }}"
-    if: always()
-    steps:
-      - uses: actions/upload-artifact@v4.3.4
-        with:
-          name: sbom-scan-${{ inputs.tag }}-${{ github.run_number }}
-          path: /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}/*-sbom-scan.txt
-          overwrite: true
+  #     - name: Collect Logs
+  #       if: always()
+  #       run: |
+  #         mkdir -p /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}
+  #         mv ${{ matrix.image }}-*-scan.txt /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}
 
-      - uses: actions/upload-artifact@v4.3.4
-        with:
-          name: trivy-scan-${{ inputs.tag }}-${{ github.run_number }}
-          path: /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}/*-trivy-scan.txt
-          overwrite: true
+  # upload-artifacts:
+  #   needs: scan-docker
+  #   runs-on: "docker-build-${{ inputs.node }}"
+  #   if: always()
+  #   steps:
+  #     - uses: actions/upload-artifact@v4.3.4
+  #       with:
+  #         name: sbom-scan-${{ inputs.tag }}-${{ github.run_number }}
+  #         path: /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}/*-sbom-scan.txt
+  #         overwrite: true
 
-      - name: Remove Logs
-        run: rm -rf /tmp/scan-${{ inputs.tag }}-${{ github.run_number }} && rm -rf /tmp/sbom-action-*
+  #     - uses: actions/upload-artifact@v4.3.4
+  #       with:
+  #         name: trivy-scan-${{ inputs.tag }}-${{ github.run_number }}
+  #         path: /tmp/scan-${{ inputs.tag }}-${{ github.run_number }}/*-trivy-scan.txt
+  #         overwrite: true
+
+  #     - name: Remove Logs
+  #       run: rm -rf /tmp/scan-${{ inputs.tag }}-${{ github.run_number }} && rm -rf /tmp/sbom-action-*
