Complete the inspection of all files and exit at the end.
Signed-off-by: zepan <ze.pan@intel.com>

diff --git a/.github/workflows/path_detection.yml b/.github/workflows/path_detection.yml
--- a/.github/workflows/path_detection.yml
+++ b/.github/workflows/path_detection.yml
@@ -13,21 +13,32 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repo GenAIExamples
-      uses: actions/checkout@v4
+      - name: Clean Up Working Directory
+        run: sudo rm -rf ${{github.workspace}}/*
 
-    - name: Clone repo GenAIComps
-      run: |
-        cd ..
-        git clone https://github.com/opea-project/GenAIComps.git
+      - name: Checkout repo GenAIExamples
+        uses: actions/checkout@v4
 
-    - name: Check for missing Dockerfile paths in GenAIComps
-      run: |
-        cd GenAIExamples
-        grep -Ern 'docker build .* -f comps/.+/Dockerfile' --include='*.md' . | while IFS=: read -r file line content; do
-            dockerfile_path=$(echo "$content" | awk -F '-f ' '{print $2}' | awk '{print $1}')
-            if [[ ! -f "../GenAIComps/${dockerfile_path}" ]]; then
-                echo "Missing Dockerfile: ${dockerfile_path} (Referenced in ${file}:${line})"
-            fi
-        done
-      shell: bash
+      - name: Clone repo GenAIComps
+        run: |
+          cd ..
+          git clone https://github.com/opea-project/GenAIComps.git
+
+      - name: Check for missing Dockerfile paths in GenAIComps
+        run: |
+          cd ${{github.workspace}}
+          miss="FALSE"
+          while IFS=: read -r file line content; do
+              dockerfile_path=$(echo "$content" | awk -F '-f ' '{print $2}' | awk '{print $1}')
+              if [[ ! -f "../GenAIComps/${dockerfile_path}" ]]; then
+                  miss="TRUE"
+                  echo "Missing Dockerfile: GenAIComps/${dockerfile_path} (Referenced in GenAIExamples/${file}:${line})"
+              fi
+          done < <(grep -Ern 'docker build .* -f comps/.+/Dockerfile' --include='*.md' .)
+
+          echo $miss
+          if [[ "$miss" == "TRUE" ]]; then 
+            exit 1
+          fi
+
+        shell: bash
