Check if the contributor is submitting for the first time.
Signed-off-by: ZePan110 <ze.pan@intel.com>

diff --git a/.github/workflows/pr-chart-e2e.yml b/.github/workflows/pr-chart-e2e.yml
--- a/.github/workflows/pr-chart-e2e.yml
+++ b/.github/workflows/pr-chart-e2e.yml
@@ -29,9 +29,20 @@ jobs:
           REPO_OWNER: ${{ github.repository_owner }}
           REPO_NAME: ${{ github.event.repository.name }}
         run: |
-          echo "${COMMITTER_USERNAME}"
-          echo "${REPO_OWNER}"
-          echo "${REPO_NAME}"
+          echo ""https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/commits?author=$COMMITTER_USERNAME""
+          commits=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            "curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/commits?author=$COMMITTER_USERNAME")
+
+          # Check if the contributor has any previous commits
+          if [ $(echo "$commits" | jq '. | length') -eq 1 ]; then
+            echo "This is the first contribution by $CONTRIBUTOR."
+            if [[ "${{ github.event.pull_request.labels.*.name }}" != *"safe to test"* ]]; then
+              echo "PR does not have 'safe to test' label. Failing the job."
+              exit 1
+            else
+              echo "PR has 'safe to test' label. Proceeding."
+            fi
+          fi
 
   job1:
     name: Get-Test-Matrix
