debug.
Signed-off-by: ZePan110 <ze.pan@intel.com>

diff --git a/.github/workflows/pr-path-detection.yml b/.github/workflows/pr-path-detection.yml
--- a/.github/workflows/pr-path-detection.yml
+++ b/.github/workflows/pr-path-detection.yml
@@ -59,20 +59,24 @@ jobs:
           url_lines=$(grep -Eo '\]\(http[s]?://[^)]+\)' -r .)
           if [ -n "$url_lines" ]; then
             for url_line in $url_lines; do
+              echo $? $url_line
               url=$(echo "$url_line"|cut -d '(' -f2 | cut -d ')' -f1|sed 's/\.git$//')
+              echo $? $url_line
               path=$(echo "$url_line"|cut -d':' -f1 | cut -d'/' -f2-)
+              echo $? $url_line
               response=$(curl -I -L -s -o /dev/null -w "%{http_code}" "$url")
-              if [ "$response" -ne 200 ]; then
-                echo "**********Validation failed, try again**********"
-                response_retry=$(curl -s -o /dev/null -w "%{http_code}" "$url")
-                if [ "$response_retry" -eq 200 ]; then
-                  echo "*****Retry successfully*****"
-                else
-                  echo "Invalid link from ${{github.workspace}}/$path: $url"
-                  fail="TRUE"
-                  echo "$fail"$?
-                fi
-              fi
+              echo $? $url_line
+              # if [ "$response" -ne 200 ]; then
+              #   echo "**********Validation failed, try again**********"
+              #   response_retry=$(curl -s -o /dev/null -w "%{http_code}" "$url")
+              #   if [ "$response_retry" -eq 200 ]; then
+              #     echo "*****Retry successfully*****"
+              #   else
+              #     echo "Invalid link from ${{github.workspace}}/$path: $url"
+              #     fail="TRUE"
+              #     echo "$fail"$?
+              #   fi
+              # fi
             done
             echo "exit for:"$?
           fi
