Redefine relative path validity
Signed-off-by: ZePan110 <ze.pan@intel.com>

diff --git a/.github/workflows/pr-path-detection.yml b/.github/workflows/pr-path-detection.yml
--- a/.github/workflows/pr-path-detection.yml
+++ b/.github/workflows/pr-path-detection.yml
@@ -102,9 +102,24 @@ jobs:
               refer_path=$(echo "$png_line"|cut -d':' -f1 | cut -d'/' -f2-)
               png_path=$(echo "$png_line"|cut -d '(' -f2 | cut -d ')' -f1)
               check_path=${{github.workspace}}/$(dirname "$refer_path")/$png_path
-              if [ ! -e $check_path ]; then
-                echo "Path $png_path in file ${{github.workspace}}/$refer_path does not exist"
+              realpath $check_path
+              if [ $? -ne 0 ]; then
+                Path $png_path in file ${{github.workspace}}/$refer_path does not exist"
                 fail="TRUE"
+              else
+                url="https://github.com/opea-project/GenAIExamples/blob/main/"$(echo "$(realpath $check_path)" | sed 's|.*/GenAIExamples/||')
+                response=$(curl -s -o /dev/null -w "%{http_code}" "$url")
+                if [ "$response" -ne 200 ]; then
+                  echo "**********Validation failed, try again**********"
+                  response_retry=$(curl -s -o /dev/null -w "%{http_code}" "$url")
+                  if [ "$response_retry" -eq 200 ]; then
+                    echo "Valid link: $url"
+                  else
+                    echo "Invalid link from $check_path: $url"
+                    # echo "Invalid link from $path: $url"
+                    fail="TRUE"
+                  fi
+                fi
               fi
             done
           fi
@@ -112,6 +127,6 @@ jobs:
           if [[ "$fail" == "TRUE" ]]; then
             exit 1
           else
-            echo "All png paths exist."
+            echo "All hyperlinks are valid."
           fi
         shell: bash
